POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Video - PHP",
    "description": "Este é o 2º video",
    "duration": 400
}

###

GET http://localhost:3000/

###

GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/3bfe10ff-b269-4875-be7c-1d222e87ac2c
Content-Type: application/json

{
    "title": "Video - React",
    "description": "Este é o video sobre React",
    "duration": 400
}

###

DELETE http://localhost:3000/videos/74e6376c-b3b2-4450-ab65-f624302c17d9